### ISSUE TITLE
SSIM as loss function

### ISSUE THREAD

**Issue by ssuwal-cuny** [CSCCNY/final-project-monodepth-ccny#24]
Testing SSIM as Loss Function

**Comment by ssuwal-cuny** [comment]
First try 9b6f6048de324eb30901c9997d6fe8e18a9b866b

**Comment by ssuwal-cuny** [comment]
used `tf.image.ssim` as for loss function, no significant improvement.
Commit  64bc18c8c622d67fd86a2e9051fc93cf32d14f62

**Comment by ssuwal-cuny** [comment]
used `tf.image.ssim_multiscale` for loss function, still no significant improvment
Commit 206270bc5795063c3db104ceb164895e4ed9a021

**Comment by ehoxha91** [comment]
Thanks for fixing it Santosh!

**Comment by ehoxha91** [comment]
In my case using a custom loss: 0.5*SSIM + 0.5*MSE it worked! It seems that we get more details than using MSE only.
