### ISSUE TITLE
This might be a good idea!

### ISSUE THREAD

**Issue by ehoxha91** [CSCCNY/final-project-monodepth-ccny#9]
It is a good idea, it might help to achieve better results, but we do not care about segmentation for now...

**Comment by ssuwal-cuny** [comment]
Something like [this](https://github.com/qubvel/segmentation_models)?

**Comment by ehoxha91** [comment]
Quite useful link Santosh!

**Comment by ehoxha91** [comment]
We decided to avoid this!
